name: Firebase Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Test"
  push:
    branches: [ "**" ]

jobs:
  buildDev:
    name: Dev Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    environment: testGitHubProfile.dev

    steps:
      - uses: actions/checkout@v3
      - name: Slack Message
        id: slack-message
        run: |
            slack_message="
            *Mention:* @devfe
            *Branch:* `${{ github.ref_name }}`
            *Environment:* <http://www.example.com|${{ vars.NODE_ENV }}>"

            echo 'slack-message<<EOF' >> $GITHUB_OUTPUT
            echo "$slack_message" >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
      - name: Slack Deploy Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Deploy Status Bot
          SLACK_CHANNEL: product-deployments
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          MSG_MINIMAL: commit,actions url
          SLACK_TITLE: Deploy information (TEST IGNORE)
          SLACK_MESSAGE: ${{ steps.slack-message.outputs.slack-message }}
          SLACK_FOOTER: "@devfe"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install
        run: |
          echo "Test variable : ${{ vars.TEST_VARIABLE }}"
          npm install
          npm run build
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  buildProd:
    name: Prod Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    environment: testGitHubProfile.prod

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install
        run: |
          echo "Test variable : ${{ vars.TEST_VARIABLE }}"
          npm install
          npm run build
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deployToProd:
    name: Deploy To Production
    needs: buildProd
    runs-on: ubuntu-latest
    environment:
      name: testGitHubProfile.prod
      url: https://vdmk-github-actions.web.app/
    steps:
      - uses: actions/checkout@v3
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy To Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

  deployToDev:
    name: Deploy To Dev
    needs: buildDev
    runs-on: ubuntu-latest
    environment:
      name: testGitHubProfile.dev
      url: https://vdmk-github-actions.web.app/
    steps:
      - uses: actions/checkout@v3
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy To Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'